### ISSUE TITLE
GPU hang on iris Plus driver

### ISSUE THREAD

**Issue by fsedano** [ngscopeclient/scopehal-apps#325] opened 2021-04-28 22:38 UTC
Getting frequent GPU hangs on Iris plus driver, with Ubuntu 20:

```
ontext: OpenGL 4.6 compatibility profile
    GL_VENDOR                   = Intel
    GL_RENDERER                 = Mesa Intel(R) Iris(R) Plus Graphics 655 (CFL GT3)
    GL_VERSION                  = 4.6 (Core Profile) Mesa 20.2.6
    GL_SHADING_LANGUAGE_VERSION = 4.60
    Initial GL error code       = 0
    GL_ARB_gpu_shader_int64     = supported

```
Dmesg:
```
[  249.432427] i915 0000:00:02.0: [drm] Resetting rcs0 for preemption time out
[  249.432440] i915 0000:00:02.0: [drm] glscopeclient[2070] context reset due to GPU hang
[  249.442335] i915 0000:00:02.0: [drm] GPU HANG: ecode 9:1:8ed8fff3, in glscopeclient [2070]
```

Demo at:
[gpu hang](https://youtu.be/5vFP06t51SU)

Capture of the hang:

https://cisco.box.com/s/frr2mo8sww7yq79csewltegc4y2rfz5k

**Comment by azonenberg** [comment] 2021-04-30 09:15
Suspect it's related to #327 but keeping this ticket open until we've confirmed that's the case.

**Comment by azonenberg** [comment] 2021-05-03 01:21
Fixed by https://github.com/azonenberg/scopehal/pull/450

**Comment by fsedano** [comment] 2021-05-07 23:35
Hi - This happened again even after the fix. Something else is going on. Same signature...

**Comment by mandl** [comment] 2022-01-28 11:32
Hello Team,

same on my Ubuntu 20.

Context: OpenGL 4.6 compatibility profile
    GL_VENDOR                   = Intel
    GL_RENDERER               = Mesa Intel(R) UHD Graphics (CML GT2)
    GL_VERSION                  = 4.6 (Core Profile) Mesa 21.0.3
    GL_SHADING_LANGUAGE_VERSION = 4.60
    Initial GL error code       = 0
    GL_ARB_gpu_shader_int64     = supported
Requested rendering backend: OpenGL
Using rendering backend: OpenGL


[ 2169.694889] i915 0000:00:02.0: [drm] Resetting rcs0 for preemption time out
[ 2169.694914] i915 0000:00:02.0: [drm] glscopeclient[9966] context reset due to GPU hang
[ 2169.700445] i915 0000:00:02.0: [drm] GPU HANG: ecode 9:1:8ed8fff3, in glscopeclient [9966]

**Comment by mandl** [comment] 2022-01-28 16:20
Workaround - use the old driver

`MESA_LOADER_DRIVER_OVERRIDE=i965 glscopeclient `

https://linuxreviews.org/Intel_Iris

**Comment by azonenberg** [comment] 2023-03-09 18:32
Is anyone still seeing this issue with recent builds and/or ngscopeclient?

**Comment by smunaut** [comment] 2023-03-13 09:02
FWIW:

```
[9485860.755044] i915 0000:00:02.0: GPU HANG: ecode 7:1:0xfefffffe, in ngscopeclient [13528], hang on rcs0
[9485860.755087] i915 0000:00:02.0: Resetting chip for hang on rcs0
```

But it's on a Haswell with incomplete vulkan support.

**Comment by azonenberg** [comment] 2023-12-06 11:05
Has anyone seen Intel driver issues with a relatively recent build? I know we fixed some shader bugs over the summer. Would like to close this if it's not still happening.

**Comment by smunaut** [comment] 2023-12-06 15:17
It's still there, just reproduced it instantly in a build of master right now.
Running on intel 12th gen iGPU with Mesa 23.3.0

**Closed** 2024-01-28 17:14 UTC
Labels: bug
