### ISSUE TITLE
View color ramp setting is not saved / restored in *.scopesession

### ISSUE THREAD

**Issue by bvernoux** [ngscopeclient/scopehal-apps#433] opened 2022-06-17 09:41 UTC
Issue reproduced with latest version of glscopeclient https://github.com/glscopeclient/scopehal-apps/commit/af2c022e85fbb9905960ebc272c86d3319ccc196 on windows 10 (using https://github.com/glscopeclient/scopehal-apps/suites/6973742607/artifacts/272626580)
View => color ramp setting is not saved / restored in *.scopesession
Can be easily reproduced with any signal displaying for example an Eyepattern with View->Color ramp different from default CRT (example if we choose Rainbow we save the sessions and restore it, it will restore default View->Color ramp => CRT)

**Comment by azonenberg** [comment] 2022-06-17 14:52
The current color ramp was intended to be a user preference, not a file setting (i.e. it should follow the user and if you load a scopesession on another user's workstation it should use their preferred colors).

It's not currently saved as such. We should have a greater discussion as to whether it makes sense for this to be a per-file or per-user setting.

Also, I'd like to be able to have more than one ramp selected for different uses (e.g. eye patterns and spectrograms might not be best to use the same ramp).

**Comment by bvernoux** [comment] 2022-06-17 15:49
Yes that feature clearly requires refactoring to be stored with scopesession per chan requiring it
Short term could be to have a way to change globally the default "View->Color ramp" to something different from default "CRT" (as it is clearly ugly)

**Comment by azonenberg** [comment] 2023-11-03 20:52
Fixed in ngscopeclient from day one, glscopeclient is deprecated so closing this

**Closed by azonenberg** 2023-11-03 20:52 UTC
