### ISSUE TITLE
File Dialog Bookmark does not work on OSX

### ISSUE THREAD

**Issue by mpangch** [ngscopeclient/scopehal-apps#669] opened 2024-01-13 05:23 UTC
On OSX (14.2) - the file dialog bookmark interface appears to allow a path bookmark to be saved, however - when the dialog is closed and subsequently relaunched - the bookmark list is empty , suggesting that the bookmark was not successfully saved.

**Comment by azonenberg** [comment] 2024-01-28 01:46
Closing as duplicate of #620

**Closed by azonenberg** 2024-01-28 01:46 UTC
